-- Migration: Create pending_otps table for self-managed OTP verification
-- This table stores OTP codes generated by the application for email verification

CREATE TABLE IF NOT EXISTS pending_otps (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email TEXT NOT NULL,
    otp_code TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast lookups by email
CREATE INDEX IF NOT EXISTS idx_pending_otps_email ON pending_otps(email);

-- Allow service role to manage this table (no RLS needed - server-side only)
ALTER TABLE pending_otps ENABLE ROW LEVEL SECURITY;

-- Policy: Only service role can access this table (no client access)
-- The service role key bypasses RLS, so no policies needed for server-side access
